packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - argon2
  - esbuild
  - prisma
