/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as LandingTermsRouteImport } from './routes/_landing/terms'
import { Route as LandingTeamRouteImport } from './routes/_landing/team'
import { Route as LandingPrivacyRouteImport } from './routes/_landing/privacy'
import { Route as LandingContactRouteImport } from './routes/_landing/contact'
import { Route as LandingAboutRouteImport } from './routes/_landing/about'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DashboardUsersIndexRouteImport } from './routes/dashboard/users/index'
import { Route as DashboardPostsIndexRouteImport } from './routes/dashboard/posts/index'
import { Route as LandingPostsIndexRouteImport } from './routes/_landing/posts/index'
import { Route as LandingAccountIndexRouteImport } from './routes/_landing/account/index'
import { Route as DashboardUsersUserIdRouteImport } from './routes/dashboard/users/$userId'
import { Route as DashboardPostsPostIdRouteImport } from './routes/dashboard/posts/$postId'
import { Route as LandingPostsPostIdRouteImport } from './routes/_landing/posts/$postId'

const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingTermsRoute = LandingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LandingRoute,
} as any)
const LandingTeamRoute = LandingTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPrivacyRoute = LandingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LandingRoute,
} as any)
const LandingContactRoute = LandingContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LandingRoute,
} as any)
const LandingAboutRoute = LandingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LandingRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/_auth/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersIndexRoute = DashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsIndexRoute = DashboardPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const LandingPostsIndexRoute = LandingPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => LandingRoute,
} as any)
const LandingAccountIndexRoute = LandingAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => LandingRoute,
} as any)
const DashboardUsersUserIdRoute = DashboardUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPostsPostIdRoute = DashboardPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const LandingPostsPostIdRoute = LandingPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => LandingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/': typeof LandingIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof LandingAboutRoute
  '/contact': typeof LandingContactRoute
  '/privacy': typeof LandingPrivacyRoute
  '/team': typeof LandingTeamRoute
  '/terms': typeof LandingTermsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/posts/$postId': typeof LandingPostsPostIdRoute
  '/dashboard/posts/$postId': typeof DashboardPostsPostIdRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/account/': typeof LandingAccountIndexRoute
  '/posts/': typeof LandingPostsIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof LandingAboutRoute
  '/contact': typeof LandingContactRoute
  '/privacy': typeof LandingPrivacyRoute
  '/team': typeof LandingTeamRoute
  '/terms': typeof LandingTermsRoute
  '/': typeof LandingIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/posts/$postId': typeof LandingPostsPostIdRoute
  '/dashboard/posts/$postId': typeof DashboardPostsPostIdRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/account': typeof LandingAccountIndexRoute
  '/posts': typeof LandingPostsIndexRoute
  '/dashboard/posts': typeof DashboardPostsIndexRoute
  '/dashboard/users': typeof DashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_landing': typeof LandingRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_landing/about': typeof LandingAboutRoute
  '/_landing/contact': typeof LandingContactRoute
  '/_landing/privacy': typeof LandingPrivacyRoute
  '/_landing/team': typeof LandingTeamRoute
  '/_landing/terms': typeof LandingTermsRoute
  '/_landing/': typeof LandingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_landing/posts/$postId': typeof LandingPostsPostIdRoute
  '/dashboard/posts/$postId': typeof DashboardPostsPostIdRoute
  '/dashboard/users/$userId': typeof DashboardUsersUserIdRoute
  '/_landing/account/': typeof LandingAccountIndexRoute
  '/_landing/posts/': typeof LandingPostsIndexRoute
  '/dashboard/posts/': typeof DashboardPostsIndexRoute
  '/dashboard/users/': typeof DashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/team'
    | '/terms'
    | '/dashboard/'
    | '/posts/$postId'
    | '/dashboard/posts/$postId'
    | '/dashboard/users/$userId'
    | '/account/'
    | '/posts/'
    | '/dashboard/posts/'
    | '/dashboard/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/team'
    | '/terms'
    | '/'
    | '/dashboard'
    | '/posts/$postId'
    | '/dashboard/posts/$postId'
    | '/dashboard/users/$userId'
    | '/account'
    | '/posts'
    | '/dashboard/posts'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/dashboard'
    | '/_landing'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_auth/verify-email'
    | '/_landing/about'
    | '/_landing/contact'
    | '/_landing/privacy'
    | '/_landing/team'
    | '/_landing/terms'
    | '/_landing/'
    | '/dashboard/'
    | '/_landing/posts/$postId'
    | '/dashboard/posts/$postId'
    | '/dashboard/users/$userId'
    | '/_landing/account/'
    | '/_landing/posts/'
    | '/dashboard/posts/'
    | '/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LandingRoute: typeof LandingRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/terms': {
      id: '/_landing/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LandingTermsRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/team': {
      id: '/_landing/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LandingTeamRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/privacy': {
      id: '/_landing/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LandingPrivacyRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/contact': {
      id: '/_landing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LandingContactRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/about': {
      id: '/_landing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LandingAboutRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users/': {
      id: '/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof DashboardUsersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/': {
      id: '/dashboard/posts/'
      path: '/posts'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof DashboardPostsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_landing/posts/': {
      id: '/_landing/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof LandingPostsIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/account/': {
      id: '/_landing/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof LandingAccountIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/dashboard/users/$userId': {
      id: '/dashboard/users/$userId'
      path: '/users/$userId'
      fullPath: '/dashboard/users/$userId'
      preLoaderRoute: typeof DashboardUsersUserIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/posts/$postId': {
      id: '/dashboard/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/dashboard/posts/$postId'
      preLoaderRoute: typeof DashboardPostsPostIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_landing/posts/$postId': {
      id: '/_landing/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof LandingPostsPostIdRouteImport
      parentRoute: typeof LandingRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPostsPostIdRoute: typeof DashboardPostsPostIdRoute
  DashboardUsersUserIdRoute: typeof DashboardUsersUserIdRoute
  DashboardPostsIndexRoute: typeof DashboardPostsIndexRoute
  DashboardUsersIndexRoute: typeof DashboardUsersIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPostsPostIdRoute: DashboardPostsPostIdRoute,
  DashboardUsersUserIdRoute: DashboardUsersUserIdRoute,
  DashboardPostsIndexRoute: DashboardPostsIndexRoute,
  DashboardUsersIndexRoute: DashboardUsersIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LandingRouteChildren {
  LandingAboutRoute: typeof LandingAboutRoute
  LandingContactRoute: typeof LandingContactRoute
  LandingPrivacyRoute: typeof LandingPrivacyRoute
  LandingTeamRoute: typeof LandingTeamRoute
  LandingTermsRoute: typeof LandingTermsRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LandingPostsPostIdRoute: typeof LandingPostsPostIdRoute
  LandingAccountIndexRoute: typeof LandingAccountIndexRoute
  LandingPostsIndexRoute: typeof LandingPostsIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingAboutRoute: LandingAboutRoute,
  LandingContactRoute: LandingContactRoute,
  LandingPrivacyRoute: LandingPrivacyRoute,
  LandingTeamRoute: LandingTeamRoute,
  LandingTermsRoute: LandingTermsRoute,
  LandingIndexRoute: LandingIndexRoute,
  LandingPostsPostIdRoute: LandingPostsPostIdRoute,
  LandingAccountIndexRoute: LandingAccountIndexRoute,
  LandingPostsIndexRoute: LandingPostsIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LandingRoute: LandingRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
